### PR TITLE
Fix compile on early 32-bit GCC

### PR DESCRIPTION
**Pull request by noloader**
Fix failed compile on 32-bit Ubuntu 4 with GCC 3.3.  Both `_mm_set_epi32` and `_mm_set_epi64x` require `<emmintrin.h>` per [Intel Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide).

### CODE REVIEW

**Comment by sneves** [comment]
Was this not actually a bug?

**Comment by noloader** [comment]
Hi @sneves.

It turned out to be an incomplete remediation. That is, when I performed a clean room build, it did not actually fix the problem I was working on. After adding the `#include <emmintrin.h>`:

```
gcc b2sum.c ../sse/blake2b.c ../sse/blake2s.c ../sse/blake2bp.c ../sse/blake2sp.c  -I/usr/local/include -DNDEBUG -g2 -O2 -fPIC -pthread -std=c99 -I. -I../sse -msse2  -o b2sum
In file included from b2sum.c:27:
../sse/blake2.h:15:9: warning: #pragma once is obsolete
In file included from ../sse/blake2b.c:20:
../sse/blake2.h:15:9: warning: #pragma once is obsolete
In file included from ../sse/blake2b.c:21:
../sse/blake2-impl.h:15:9: warning: #pragma once is obsolete
In file included from ../sse/blake2b.c:23:
../sse/blake2-config.h:15:9: warning: #pragma once is obsolete
In file included from ../sse/blake2b.c:42:
../sse/blake2b-round.h:15:9: warning: #pragma once is obsolete
../sse/blake2b.c: In function `blake2b_compress':
../sse/blake2b.c:304: warning: implicit declaration of function `_mm_set_epi64x'../sse/blake2b.c:304: error: incompatible types in assignment
../sse/blake2b.c:304: error: incompatible types in assignment
../sse/blake2b.c:304: error: incompatible types in assignment
../sse/blake2b.c:304: error: incompatible types in assignment
...
```

I _think_ the issue is, GCC 3.3 is old, and it does not include `_mm_set_epi64x`.

I also think the fix may be something like (assuming GCC 4.0 provides it):

```
#if GCC_VERSION >= 40000
#  define MM_SET_EPI64X(a,b) _mm_set_epi64x((a),(b))
#else
#  define MM_SET_EPI64X(a,b) \
    <some definition here>
#endif
```

**Comment by noloader** [comment]
@sneves,

I was able to clear the compile problem using GCC with [commit e16f0079da1d](https://github.com/noloader/BLAKE2/commit/e16f0079da1d). The body for `MM_SET_EPI64X_IMPL` was mostly lifted from GCC's `_mm_set_epi64x` (which had a 64-bit guard).

```
#if defined(__amd64__) || defined(__x86_64__) || defined(_M_X64)
#  define BLAKE2_X64_MACHINE 1
#endif

#if defined(BLAKE2_X64_MACHINE)
#  define MM_SET_EPI64X(a,b) \
     _mm_set_epi64x(a,b)
#elif defined(__GNUC__)
#  define MM_SET_EPI64X(a,b) \
     MM_SET_EPI64X_IMPL(a,b)

   static __inline __m128i
   MM_SET_EPI64X_IMPL (long long x, long long y)
   {
     union {
       long long a[2];
       __m128i v;
     } u;

     u.a[0] = y;
     u.a[1] = x;

     return u.v;
   }
#else
#  define MM_SET_EPI64X(a,b) \
     _mm_set_epi32((unsigned int)(a),(a)>>32,(unsigned int)(b),(b)>>32)
#endif

#define LOAD_MSG_0_1(b0, b1) b0 = MM_SET_EPI64X(m2, m0); b1 = MM_SET_EPI64X(m6, m4)
#define LOAD_MSG_0_2(b0, b1) b0 = MM_SET_EPI64X(m3, m1); b1 = MM_SET_EPI64X(m7, m5)
#define LOAD_MSG_0_3(b0, b1) b0 = MM_SET_EPI64X(m10, m8); b1 = MM_SET_EPI64X(m14, m12)
#define LOAD_MSG_0_4(b0, b1) b0 = MM_SET_EPI64X(m11, m9); b1 = MM_SET_EPI64X(m15, m13)
...
```

I'm not sure about the non-GCC code path. MSVC may be able to use it.

The next problem is, both BLAKE2b and BLAKE2s both crash the compiler :)

**Comment by sneves** [comment]
I could swear I had run into something like this before...and I had, with [Visual Studio](https://github.com/BLAKE2/libb2/blob/master/src/blake2b.c#L27-L36).
